---
name: Check 🛠

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main

# Prerequisites to run workflows:
# Actions -> I understand my workflows...
# Settings -> Actions -> General -> Workflow permissions -> Read and write permissions
# Create a PR from your own branch to main.

# This reusable workflow from insightsengineering/r.pkg.template will run once a PR to main branch is created.
jobs:
  job-setup:
    name: Should we run R CMD check?
    runs-on: ubuntu-latest
    outputs:
      check_out: ${{ steps.check.outputs.run_r_cmd_check }}
    steps:
      - name: To check or not to check?
        id: check
        run: |
          echo "run_r_cmd_check=false" >> $GITHUB_OUTPUT

  r-cmd:
    name: R CMD Check 🧬
    needs: job-setup
    # Call a workflow from a given GitHub repository, from a given branch (or tag).
    uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@main
    if: >
      needs.job-setup.outputs.check_out == 'true'
